### ISSUE TITLE
problem does not recognize the plugin correctly

### ISSUE THREAD

**Issue by dobregon96** [DrAbcOfficial/lagcompensator#1]
Good, apparently you have a plugin recognition error, it does not recognize it when the svencoop server starts

**Comment by DrAbcOfficial** [comment]
[metamod-fallguys](https://github.com/hzqst/metamod-fallguys)

Only this version of Metamod is supported. If there are other ABI issues, please try recompiling

**Comment by dobregon96** [comment]
> [metamod-fallguys](https://github.com/hzqst/metamod-fallguys)
> 
> Only this version of Metamod is supported. If there are other ABI issues, please try recompiling

**Comment by dobregon96** [comment]
> [metamod-fallguys](https://github.com/hzqst/metamod-fallguys)
> 
> Only this version of Metamod is supported. If there are other ABI issues, please try recompiling

**Comment by dobregon96** [comment]
Couldn't load game library "/home/server/sv/svencoop/addons/metamod/dlls/metamod.so"
Reason: /home/server/sv/svencoop/addons/metamod/dlls/metamod.so: undefined symbol: _ZN7procmap13MemorySegment12startAddressEv
Host_Error: No valid game library could be found!
FATAL ERROR (shutting down): Host_Error: No valid game library could be found!
I get this problem when I want to start the server with metamod fallguys, I don't know what it is, the operating system I use is debian 10
