### ISSUE TITLE
problems with the plugin it doesn't open even though I have metamod fallguys installed correctly

### ISSUE THREAD

**Issue by dobregon96** [DrAbcOfficial/lagcompensator#2]
Couldn't load game library "/home/zj20u/Fenix/svencoop/addons/metamod/dlls/metamod.so"
Reason: /home/zj20u/Fenix/svencoop/addons/metamod/dlls/metamod.so: undefined symbol: _ZN7procmap13MemorySegment12startAddressEv
Host_Error: No valid game library could be found!
FATAL ERROR (shutting down): Host_Error: No valid game library could be found!

I get this problem when I want to start the server with metamod fallguys, I don't know what it is, the operating system I use is debian 10

**Comment by DrAbcOfficial** [comment]
Please check the version of your dependency libraries,
this problem is a metamod issue and I won't deal with it here
If you want to use the plugin under another version of metamod, please recompile under another metamod
